/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/domain/ModelTest.e.vm.java
 */
package com.yourcompany.yourproject.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.yourcompany.yourproject.util.ValueGenerator;

/**
 * Basic tests for Book
 */
public class BookTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Book model = new Book();
        assertFalse(model.isPrimaryKeySet());
    }

    @Test
    public void isPrimaryKeySetReturnsTrue() {
        Book model = new Book();
        model.setBookId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));
        assertNotNull(model.getBookId());
        assertTrue(model.isPrimaryKeySet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  Book.accountId ==> Account.accountId
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setAccount() {
        Book many = new Book();

        // init
        Account one = new Account();

        one.setAccountId(ValueGenerator.getUniqueString(32));
        many.setAccount(one);

        // make sure it is propagated properly
        assertNotNull(many.getAccountId());
        assertEquals(one, many.getAccount());
        assertSame(many.getAccountId(), one.getAccountId());
        // now set it to back to null
        many.setAccount(null);

        // make sure null is propagated properly
        assertNull(many.getAccount());

        // make sure it is propagated on fk column as well
        assertNull(many.getAccountId());
    }

    @Test
    public void toStringNotNull() {
        Book model = new Book();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        Book model1 = new Book();
        Book model2 = new Book();

        Integer bookId = ValueGenerator.getUniqueNumeric(Integer.class, "2147483647");
        model1.setBookId(bookId);
        model2.setBookId(bookId);

        model1.setTitle("d");
        model2.setTitle("d");

        model1.setNumberOfPages(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        model2.setNumberOfPages(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));

        model1.setVersion(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        model2.setVersion(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        assertTrue(model1.isPrimaryKeySet());
        assertTrue(model2.isPrimaryKeySet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}