/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/domain/ModelTest.e.vm.java
 */
package com.yourcompany.yourproject.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.yourcompany.yourproject.util.ValueGenerator;

/**
 * Basic tests for Document
 */
public class DocumentTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Document model = new Document();
        assertFalse(model.isPrimaryKeySet());
    }

    @Test
    public void isPrimaryKeySetReturnsTrue() {
        Document model = new Document();
        model.setDocumentId(ValueGenerator.getUniqueString(32));
        assertNotNull(model.getDocumentId());
        assertTrue(model.isPrimaryKeySet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  Document.accountId ==> Account.accountId
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setAccount() {
        Document many = new Document();

        // init
        Account one = new Account();

        one.setAccountId(ValueGenerator.getUniqueString(32));
        many.setAccount(one);

        // make sure it is propagated properly
        assertNotNull(many.getAccountId());
        assertEquals(one, many.getAccount());
        assertSame(many.getAccountId(), one.getAccountId());
        // now set it to back to null
        many.setAccount(null);

        // make sure null is propagated properly
        assertNull(many.getAccount());

        // make sure it is propagated on fk column as well
        assertNull(many.getAccountId());
    }

    @Test
    public void toStringNotNull() {
        Document model = new Document();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        Document model1 = new Document();
        Document model2 = new Document();

        String documentId = ValueGenerator.getUniqueString(32);
        model1.setDocumentId(documentId);
        model2.setDocumentId(documentId);

        model1.setDocumentContentType("d");
        model2.setDocumentContentType("d");

        model1.setDocumentSize(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        model2.setDocumentSize(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));

        model1.setDocumentFileName("d");
        model2.setDocumentFileName("d");

        model1.setDocumentBinary("d".getBytes());
        model2.setDocumentBinary("d".getBytes());

        model1.setVersion(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        model2.setVersion(ValueGenerator.getNumeric(java.lang.Integer.class, "1"));
        assertTrue(model1.isPrimaryKeySet());
        assertTrue(model2.isPrimaryKeySet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}